# Generated by Django 4.0.4 on 2022-05-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tougshire_history', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='app_label',
            field=models.CharField(default='', help_text='The app to which this change applies', max_length=50, verbose_name='app label'),
            preserve_default=False,
        ),
    ]
